### PR TITLE
Update logistic.py - comments for funcs, header

### PR DESCRIPTION
**Pull request by LiamDuncan**
"Added block comments to the top of project/each method to justify decisions and give context to the purpose of certain functions."

### CODE REVIEW

**Comment by perborgen** [comment]
Awesome!

**Comment by LiamDuncan** [comment]
I don't think i affected or changed any of the actual code so it should be
working. This was for an assignment btw but i hope the comments are also
helpful.

**Comment by perborgen** [comment]
Very helpful indeed!

**Comment by LiamDuncan** [comment]
Alright cool.

**Pull request merged**
